---
- name: Full site run (web + patch + firewall)
  hosts: all
  serial: 10 # rolling batches of 10 hosts
  max_fail_percentage: 20
  strategy: free # can use linear/rolling via serial
  gather_facts: true

  roles:
    - role: patch
      tags: patch

    - role: firewall
      tags: firewall

- import_playbook: web.yml
